name: Build, Test and Push Docker Images with Kafka Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest

    - name: Run unit tests
      run: pytest tests/

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build API Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/lab4-kafka-app:latest .

    - name: Push API Docker image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/lab4-kafka-app:latest
